### ISSUE TITLE
Underscores are being stripped out incorrectly in table cells

### ISSUE THREAD

**Issue by darrenburns** [willmcgugan/rich#10]
I've got a table which I created like so:

```python
    table = Table(show_header=False, padding=0, show_edge=False, box=0)
    table.add_column("outcome", style=theme, width=6, justify="center")
    table.add_column("location", style="test-location")
    table.add_column("description", style="none")

    table.add_row(outcome, location, f"{description} {reason}")
```

If the `description` contains two underscores, such as in many Python function names, the underscores are removed.

For example, in the following screenshot, the top line is the description string. The bottom line is the description as displayed in the table.

<img width="729" alt="Screenshot 2020-02-24 at 19 33 08" src="https://user-images.githubusercontent.com/5740731/75184571-82109300-573c-11ea-92be-0dd4fcbf7ca3.png">

This *doesn't* happen if the description contains a single `_`. I was guessing it was trying to render it as Markdown or something, but I get the same issue when setting `markup=False` when initialising the `Console`. 😄

**Comment by willmcgugan** [comment]
If you pass in a string to the table class, it will render it as [console markup](https://rich.readthedocs.io/en/latest/markup.html) -- which is similar in some ways to markdown. I think the way you constructed the styles has disabled the italics.

If you want to stop Table from rendering console markup, you can use `Text` instances rather than plain strings.

The `markup=False` in the  `Console` constructor will disable markup when you call `console.print` with a string. But on reflection, I think your instinct should be correct. It should disable it everywhere. I'll do that in the next release.

**Comment by darrenburns** [comment]
> I think the way you constructed the styles has disabled the italics.

Yeah, that's correct. I changed to using `push_styles` and it now renders like:
<img width="649" alt="Screenshot 2020-02-24 at 20 48 01" src="https://user-images.githubusercontent.com/5740731/75189835-f7816100-5746-11ea-8f5b-ba66b8c79ba9.png">

> If you want to stop Table from rendering console markup, you can use Text instances rather than plain strings.

Thanks! That works.

> The markup=False in the Console constructor will disable markup when you call console.print with a string. But on reflection, I think your instinct should be correct. It should disable it everywhere. I'll do that in the next release.

Cool, thanks. 😄 

Kudos on this project by the way. I've started shifting some things over and am really enjoying using the API.

**Comment by willmcgugan** [comment]
> Kudos on this project by the way. I've started shifting some things over and am really enjoying using the API.

Cheers. It's been at the back of my mind for years, every time I tried to do anything fancy in the console. Finally got round to it.
