### ISSUE TITLE
[BUG] Spinner example not working on windows

### ISSUE THREAD

**Issue by bobatsar** [willmcgugan/rich#1023]
When running 
````
python -m rich.spinner
````
the live refresh is not working and multiple new lines are generated on windows. On linux everything is fine.

I am running rich 9.11.0 on Python 3.9.1 (the error was also on Python 3.7) and tried it in git bash in windows terminal, cmd in windows terminal and also directly in cmd.

![image](https://user-images.githubusercontent.com/7723101/108348206-c4e73880-71e1-11eb-8ecf-5509bd294078.png)

**Comment by willmcgugan** [comment]
The extra lines issue is probably because the terminal isn't rendering one of the newer emojis with the correct width and its overflowing on to the next line. Rich has no way to detect this so its no able to blank out the last frame.

If you were to use spinners in your code, most would work fine. Try:

```
python -m rich.spinner
```

cmd will flicker in general, as it is ancient and it has poor support for emoji. Wether it works or not depends on your choice of font.

**Comment by willmcgugan** [comment]
Sorry..

```
python -m rich.status
```
