### ISSUE TITLE
Feature request: Screen re-/storing

### ISSUE THREAD

**Issue by timfi** [willmcgugan/rich#103]
I've been playing around with `rich` as of late and I am really enjoying it. :+1:
But there is one thing I wish was also in this wonderful chuck of code and that would be the ability to programmatically store and restore the terminal view (Like how `less` and other common commandline utilities do). I've got a somewhat working version of a decorator that I am using in my current project which I think some other people might find fairly useful. ;)

```python
from contextlib import contextmanager
import subprocess

@contextmanager
def second_screen():
    try:
        r_code, s_code = (
            subprocess.getoutput(
                r"infocmp -1 | grep 'rmcup\|smcup' | sed 's/.*=\(.*\),/\1/'"
            )
            .replace("\\E", "\033")
            .split("\n")
        )
        try:
            print(s_code + "\033[0;0H", end="")
            yield
        finally:
            print(r_code, end="")
            return
    except:
        yield
```

I tried my hand at making it work with multiple different terminals by using `infocmp` to findout the proper escape sequence.

I am unsure if this is something that is considered inside the scope of this library, but imho I think it would by a great addition. I think the best way to integrate this into the API would be to add it as a member of the `Console`-class to enable the following usage:

```python
from rich.console import Console

console = Console()

with console.second_screen():
    console.print("It works!", style="bold green")
```

EDIT: For me the escape sequences turn out to be:
```python
s_code = '\033[?1049h\033[22;0;0t'
r_code = '\033[?1049l\033[23;0;0t'
```
So switch to secondary/primary buffer and re-/store icon and window title from/to stack respectively.

**Comment by willmcgugan** [comment]
Hi @tim-fi 

Glad you like Rich. I was planning on implementing a pager like less, so I would need something along these lines. Thanks for doing the research on that.

**Comment by tim-fi** [comment]
Yeah I saw that issue and was wondering to myself if I should simply give my two cents there, but I think the nicest way would be expose this kind of functionality to the user and then simply also use it for the pager.

Additionally I just did some digging, trying to find out if something like this could work on windows. (Obviously my implementation above does not due to the use of *nix commands to find out the control sequences…) And it turns out their Windows Console actually support at least the important sequences, at least according to their [docs]( https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#alternate-screen-buffer).

**Comment by tim-fi** [comment]
I was wondering how some other project (though in other languages) achieve a similar effect in terminals that don't support ANSI escape sequences and stumbled upon version of `less` that works on windows. They seem to either [create a new `ConsoleScreenBuffer` using `windows.h`](https://github.com/adoxa/less/blob/master/screen.c#L1491-L1529) or [simply print new lines until the screen is full](https://github.com/adoxa/less/blob/master/screen.c#L1589-L1612).

PS: @willmcgugan I'm looking further into this on my own volition with no strings attached. I'm simply curious myself atm and thought that you might find some of the things I find use since have to some lengths to make `rich` as cross-platform as possible. :+1:

**Comment by willmcgugan** [comment]
I'd probably not bother with legacy windows now that there is the option of the new Windows Terminal. Unless there is a low cost compatibility layer, like colorama.

Let me know what your research turns up!

**Comment by tim-fi** [comment]
So my final verdict is that this is only possible in cmd.exe if you use the low-level windows c api, as such I think the legacy support isn't really an option.

(This may not be 100% accurate but some people with a lot of points on SO seemed to come to [this conclusion](https://stackoverflow.com/questions/62267123/alternate-screen-buffer-for-the-windows-console).)

**Comment by willmcgugan** [comment]
I feared as much!

**Comment by willmcgugan** [comment]
Closing this to tidy issues, but keeping a note of it.
