### ISSUE TITLE
[BUG] Inconsistent tag escaping when encountering numeric values

### ISSUE THREAD

**Issue by karolpiczak** [willmcgugan/rich#1178]
The escaping mechanics are a bit confusing when the content after the square brackets might start with a digit.

**To reproduce:**
```python
from rich import print

msgs = [
        '[bold yellow] Hello world!',
        '[bold yellow] [words that will be stripped] Nothing here... apart from an extra space...',
        '[bold yellow] \[words that will show] Escaping works.',
        '[bold yellow] \[4 words that will show] Not anymore...',
        '[bold yellow] [4 words that will show] Huh?'
]

for msg in msgs:
    print(msg)
```

![image](https://user-images.githubusercontent.com/215618/115562976-555ff900-a2b7-11eb-977c-9d2801a4d4c9.png)

Differentiating between such cases is doable when writing it explicitly, but it is a bit more cumbersome when using something like this:

```python
from rich import print

levels = ['info', 'debug', '42']

for level in levels:
    print(f'[bold yellow] \[main] \[{level}]')
```

![image](https://user-images.githubusercontent.com/215618/115565563-c4d6e800-a2b9-11eb-80fd-e2180086ac75.png)

**Comment by willmcgugan** [comment]
A style can't start with a number so "[4 words etc]" doesn't need escaping.

This is so that you can print a list containing a number without it being considered a style tag. If you are surprised by this, bear in mind that the alternative would be that you couldn't print something like `[42]` (literal list) without escaping it.

If you are generating any strings containing console markup, you should use `rich.markup.escape` and these problems will go away.

**Comment by karolpiczak** [comment]
I assumed that string representations of literal lists will be handled in the same way as any other string.

The problem with `rich.markup.escape` is its inconvenience in some cases. I think the syntax is readable for things like this:

```python
from rich.console import Console
from rich.markup import escape

console = Console()

name = 'test'
console.print(f'Hello {escape(name)}')
```

When dynamically creating strings with square brackets (e.g. expected output of `Hello [test]`) this would require nested f-strings:
```python
console.print(f'Hello {escape(f"[{name}]")}')
```

In my use case I've ended up using a helper "unescaper":
```python
import re
from typing import Match

from rich import print

def print_(markup: str, _unescape=re.compile(r"(\\*)(\[[^a-z#\/].*?\])").sub):
    def unescape_backslashes(match: Match[str]) -> str:
        """Called by re.sub replace matches."""
        _, text = match.groups()
        return text

    markup = _unescape(unescape_backslashes, markup)
    print(markup)
```

This allows for shorter syntax when creating messages with square brackets:
```python
print_(f'Hello {escape(name)}')
print_(f'Hello \[{escape(name)}]')
```

This is especially convenient when substituted fields don't require additional escaping:
```python
t = ['lorem', 'ipsum', '42', 'dolor']

print(f'[bold red] {escape(f"[{t[0]}]")} [green] {escape(f"[{t[1]}]")} [blue] {escape(f"[{t[2]}]")} [white] {escape(f"[{t[3]}]")}')
print_(f'[bold red] \[{t[0]}] [green] \[{t[1]}] [blue] \[{t[2]}] [white] \[{t[3]}]')
```

**Comment by willmcgugan** [comment]
I would agree that the proliferation of escapes doesn't aid readability, especially when within an f string. However I think a better solution would be to factor those `escape(f"[{t[0]}]")` expressions in to variables, i.e. `foo=escape(f"[{t[0]}]")`. So your f string need only contain "[bold red] {foo} ...". 

At that point I would probably also consider using a Text instance rather than markup.
