### ISSUE TITLE
[BUG] python3.10 test failures

### ISSUE THREAD

**Issue by jsmolic** [willmcgugan/rich#1216]
When running tests with Python 3.10.0b1 (Gentoo Linux), the following tests fail:
```
FAILED tests/test_inspect.py::test_inspect_integer_with_methods - assert ("╭──────────────── <class 'int'> ─────────────────╮...
FAILED tests/test_log.py::test_log - AssertionError: assert ('\x1b[2;36m[TIME]\x1b[0m\x1b[2;36m '\n '\x1b[0m                 ...
FAILED tests/test_pretty.py::test_pretty_dataclass - assert "ExampleDataclass(foo=1000, bar='Hello, World', baz=['foo', 'bar'...
FAILED tests/test_segment.py::test_repr - assert "Segment('foo', None, [(ControlType.HOME, 0)])" == "Segment('foo', None, [
```
I'm attaching the full build log

[build.log](https://github.com/willmcgugan/rich/files/6437768/build.log)

**Comment by willmcgugan** [comment]
Those error seem to be due to a change in the repr format of various objects in Python3.10. Not a bug per-se but I'll update the tests in the next release.

**Comment by willmcgugan** [comment]
Tried to add the beta to GH Actions, but running in to [this error](https://github.com/python-poetry/poetry/issues/4056). Will come back to it when that's resolved.

**Comment by sondrelg** [comment]
@willmcgugan if this is blocking you (and is time sensitive) it looks like you should be able to get around the issue by using the plain `pip install poetry` option instead the action 👍 

In other words, if you replace lines 22-26 [here](https://github.com/willmcgugan/rich/blob/master/.github/workflows/pythonpackage.yml#L22) with

```yaml
      - run: pip install poetry
```

I believe it *should* work for you.

The reason the action doesn't currently work seems to be because it (ironically) uses the recommended installation method of fetching and executing Poetry's `get-poetry.py` script 🙂

**Comment by willmcgugan** [comment]
Thanks @sondrelg It's not terribly urgent, but I'll give that a try!

**Comment by mgorny** [comment]
Ping.

**Comment by willmcgugan** [comment]
Fixed!
