### ISSUE TITLE
[BUG] Misaligned column headers of pandas DataFrame in IPython when using rich.pretty

### ISSUE THREAD

**Issue by dlukes** [willmcgugan/rich#1256]
Compare the vanilla `Out[2]` with `Out[4]` prettified by `rich`: the column headers are no longer right-aligned:

![ipython](https://user-images.githubusercontent.com/2734517/119827507-82787a80-bef9-11eb-8831-b16d5559bae4.png)

The fix should be easy -- just make `rich` put the column headers on a separate line, like the vanilla representation. But maybe there's a catch? One thing that comes to mind is that maybe this can't be fully fixed on `rich`'s side -- maybe it's an unfortunate interaction between `rich`, `ipython` and `pandas`? FWIW, the problem doesn't occur in the regular Python REPL:

![python](https://user-images.githubusercontent.com/2734517/119828092-22360880-befa-11eb-801f-c05bd981639a.png)

**Comment by willmcgugan** [comment]
The problem is that IPython prints the `Out[2]` text and leaves the cursor at the next character, where Rich starts printing from. This is fine if you are printing something on a single line, but it breaks formatted columns as you've demonstrated.

I'm assuming that IPython has a special case for output that has newlines. If there is a newline character it will start the output on the following line and not the line containing `Out[X]`. Rich could probably replicate this behavior.

**Comment by dlukes** [comment]
> I'm assuming that IPython has a special case for output that has newlines. If there is a newline character it will start the output on the following line and not the line containing Out[X]. Rich could probably replicate this behavior.

That sounds great as far as I'm concerned :)

**Comment by willmcgugan** [comment]
Can you give 10.5.0 a try and let me know if that fixes it?

**Comment by dlukes** [comment]
Works like a charm, thank you very much!
