### ISSUE TITLE
[REQUEST] Markup=True when configuring logging RichHandler

### ISSUE THREAD

**Issue by ewels** [willmcgugan/rich#171]
**How would you improve Rich?**

The Rich logging is really nice to use, however I must admit that having to add `extra={"markup": True}` on loads of log calls bloats the code a bit.

Would it be possible to make this an option in `rich.logging.RichHandler()` as well, so that this could be enabled by default for all log messages when configuring the logger?

For example, something like:

```python
import logging
from rich.console import Console
from rich.logging import RichHandler

logging.basicConfig(
    level="NOTSET",
    format="%(message)s",
    datefmt="[%X]",
    handlers=[RichHandler(
        file=Console(file=sys.stderr),
        markup=True    ### New option
    )]
)

log = logging.getLogger("rich")
log.info("Hello, World!")

log.error("[bold red blink]Server is shutting down![/]")
# Instead of:
# log.error("[bold red blink]Server is shutting down![/]", extra={"markup": True})
```

**Comment by willmcgugan** [comment]
The `extra` arg is kind of ugly.

I wasn't keen on enabling markup in the handler, because log messages can come from libraries not under your control. If you enable logging for a dependency and that lib writes a log message containing square brackets then the contents of the square brackets will be removed or result in an unwanted style.

That said, I could add that option to RichHandler as you suggested, with a prominent warning in the docs...

**Comment by ewels** [comment]
Yes exactly - I figured that was the case and I agree it makes sense not to have it turned on by default. The `extra` arg is also fine if you only need it once or twice. It's just if you really want to pimp all of your log messages everywhere that it starts being a problem 😅

**Comment by willmcgugan** [comment]
Added the markup parameter in v4.0.0

**Comment by ewels** [comment]
Ok, that was silly fast. You haven't even triaged the issue yet and you've already pushed a release with the new feature 😆 

Amazing stuff, thank you!!
