### ISSUE TITLE
[BUG] printed text not showing up when using progress bar  in jupyter-notebook

### ISSUE THREAD

**Issue by yashrathi-git** [willmcgugan/rich#1733]
Description: printed text not showing up when using progress bar  in jupyter-notebook
![2021-12-01 20-06-31](https://user-images.githubusercontent.com/57002207/144254385-b1cbbce1-9a57-4b88-aee3-9f7f7430c2da.gif)

Provide a minimal code example that demonstrates the issue if you can. If the issue is visual in nature, consider posting a screenshot.
```py
from time import sleep
from rich.progress import track

for i in track(range(1000)):
    sleep(1)
    print("Test, is it showing?")
```

**Platform**

OS: Linux
env: jupyter-lab

I may ask you to cut and paste the output of the following commands. It may save some time if you do it now.

```
pip freeze | grep rich
```
Output:
```
rich==10.15.1
```

**Comment by yashrathi-git** [comment]
It's the same behaviour when I use rich's print function instead of builtin
```py
from time import sleep

from rich.table import Column
from rich.progress import Progress, BarColumn, TextColumn

text_column = TextColumn("{task.description}", table_column=Column(ratio=1))
bar_column = BarColumn(bar_width=None, table_column=Column(ratio=2))
progress = Progress(text_column, bar_column, expand=True)

with progress:
    for n in progress.track(range(100)):
        progress.print(n)
        sleep(0.1)
```

**Comment by sanders41** [comment]
I was not able to reproduce this to the level you can, but I was able to see it "glitch" occasionally. Running in debug mode, `jupyter lab --debug` It looks like it happens for me when Jupter is refreshing the token. When I see it glitching this is the message from the server log. 

```sh
[D 2021-12-03 10:35:36.838 ServerApp] Accepting token-authenticated connection from ::1
[D 2021-12-03 10:35:36.839 ServerApp] 200 GET /api/sessions?1938545756824 (::1) 0.93ms
```

I also tried Rich 10.15.2 and got the same results.

**Comment by willmcgugan** [comment]
This occurs in Jupyter lab, but not Jupyter notebook. I suspect a bug in Lab, because Rich doesn't differentiate between the two.

**Comment by zhaowb** [comment]
It's possible because jupyter lab version / ipywidgets installation not match:

If jupyter lab version is 1 or 2 ([see doc](https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-into-jupyterlab-1-or-2)), you'll need manually install the extension.
If jupyter lab version is 3 then it should be fine (doc is same page in above link).

To see if your jupyter lab is working as expected, please try this code
```
import time
from IPython.display import display as ipython_display
import ipywidgets
out1 = ipywidgets.Output()
out2 = ipywidgets.Output()
ipython_display(out1)
ipython_display(out2)
with out1:
    print('this is in out1')
print('outside context - where is this line ?')
with out2:
    print('this is out2')
print('outside context - where is this line *2 ?')
time.sleep(2)

with out1:
    print('more in out1')
time.sleep(1)
with out2:
    print('next in out2')
time.sleep(2)

with out1:
    out1.clear_output(wait=True)
    print('out1 is cleared, hope out2 is not')
time.sleep(2)

with out2:
    out2.clear_output(wait=True)
    print('out2 is cleared, hope out1 is not')

print('outside context - where is this line *3 ?')
```

It should have two output widgets being updated separately, meaning out1 and out2 are two different div and when out1 is cleared, out2 remains. When version/installation not correct, out1 and out2 outputs are intertwined and one clear will clear all.

I have tried in both jupyter lab 2 & 3 and see the version 3 works out of the box, and version 2 doesn't work before install extention then works after installation.

Good luck

**Comment by yashrathi-git** [comment]
@zhaowb Thanks this works
It seems to be still a problem with jupyter-lab v3.2.5 for me, but installing the extension manually fixed it.
