### ISSUE TITLE
[REQUEST] Allow ordering of columns for custom logging

### ISSUE THREAD

**Issue by Samreay** [willmcgugan/rich#202]
At the moment, I would love to convert from colorama to using Rich for my projects. However, I notice that when you define the logging handler, the format of the message is decided by the private class LogRender. Whilst you can turn things on or off in this class, I notice you cannot reorder. 

The default output looks great: 
![image](https://user-images.githubusercontent.com/6748505/89188512-1e8b6b00-d5e2-11ea-8526-e9e121a27a4f.png)

However if a user ever comes along and resizes the window (which I know happens all the time), the output becomes mangled due to the overflow wrapping caused by rich filling the horizontal buffer to right align the filename.

![image](https://user-images.githubusercontent.com/6748505/89188603-3e229380-d5e2-11ea-9260-50985f45597d.png)

I was considering simply monkey patching the LogRender class and just updating the [pathing code](https://github.com/willmcgugan/rich/blob/master/rich/_log_render.py#L47) such that I could put the filenames at the start (to some fixed-width string), but it felt a bit dirty, so perhaps there is another way of doing it, or you'd be amendable to increasing the flexibility of the LogRender options?

On a similar note, I cannot find any examples of updating the ReprHighlighter and associated new styles in the documentation (though I might have missed it!), and given that they seem to be in different places after digging through the code (the Console object has the styling under the theme, and the syntax matching is done via extending the Highlighter) I feel like this would also be a useful addition! If theres a solution to the first issue I'd also be super happy to write up a bunch of customised logging examples and submit it as a PR if that sounds like a good idea to you!

**Comment by willmcgugan** [comment]
Hi @Samreay 

I gather you are using the Windows terminal. The strange resize behaviour is caused by Windows removing the last new line character if its at the edge of the terminal - which doesn't happen on OSX and Linux. 

I see why you would want to put the filename at the start, but I'm not keen on a fixed width column for the filename. You never can be certain what a sensible maximum is, and then what do you do if a filename + line is larger than the column.

Configuration is possible, but making everything configurable does make it harder to maintain -- and I'm not sure if the demand is there to make it worthwhile. I would lean towards making it easier to extend, and making the log render class public.

Re styles, the docs on [themes](https://rich.readthedocs.io/en/latest/style.html#style-themes) cover how you can customize styles. There's also an [example](https://github.com/willmcgugan/rich/blob/master/examples/highlighter.py) that might help, and the code for [ReprHighlighter](https://github.com/willmcgugan/rich/blob/master/rich/highlighter.py#L69).

Will

**Comment by Samreay** [comment]
Hi Will!

You are completely correct! I went back and tested this on windows cmd (resizing works great), windows powershell (works great), MacOS terminal (works great) and windows ubunutu terminal (makes me sad). Windows odd choices are definitely not on you, and I completely understand the potential issues with arbitrary filename sizing, so all good!

In terms of the styling, I was going to suggest an example where you update styles and themes in one place. I can see people wanting to use all the work thats been done in the ReprHighlighter, and add to it rather than replace it. The concern was that its easy for people to clobber or modify original references given the variables are class static.

Here was a rough outline of something I was going to suggest adding in, which is designed to build on top of the existing code rather than replace it:

```python
from rich.highlighter import ReprHighlighter
from rich.console import Console
from rich.default_styles import DEFAULT_STYLES
from rich.style import Style
from rich.themes import Theme


class ExtraHighlighter(ReprHighlighter):
    # If I declare class vars, it will clobber
    # If you add an append, it will update ReprHighlighter
    # So you need to either copy/append, or add in a way you get a new ref
    highlights = ReprHighlighter.highlights + [r"(?P<name>pattern)"]
    
highlighter = ExtraHighlighter()

new_styles = {"repr.name": Style(color="green")}
# Dont want to use update, as it might the default might clobber so either recreate in 
# correct order, or .copy() the default first
styles = {**DEFAULT_STYLES, **new_styles}

console = Console(theme=Theme(styles), highlighter=highlighter)

console.log("here is the pattern")
```

**Comment by willmcgugan** [comment]
The resize thing may be a bug in Windows terminal -- I can't see why that behaviour is desirable. I'll raise that on their repos.

Themes will inherit the default styles by default. So you only need to add any new / modified styles:

```python
my_theme = Theme({"repr.name": Style(color="green")})
```

**Comment by Samreay** [comment]
Ah, thats great to know about inheriting the default style. Thanks for all the info, and rich is an amazing library!

**Comment by willmcgugan** [comment]
Glad you like it!
