### ISSUE TITLE
[REQUEST] Markup in traceback

### ISSUE THREAD

**Issue by GeekDuanLian** [willmcgugan/rich#226]
![image](https://user-images.githubusercontent.com/6257434/89778102-80e2ef00-db3f-11ea-8a80-c334f947f4bd.png)

If traceback also supports markup, it will be the best.

**Comment by willmcgugan** [comment]
Not convinced that's a good idea to enable globaly. An exception may accidentally contain something that looks like console markup but wasn't intended to be treated as markup.

I could make it optional. Perhaps if the exception had a `__rich__` method, it would use that to render the error, rather than `__str__`.

For instance, this would make a custom exception render markup:

```python
class MyError(Exception):
    def __rich__(self):
         return str(self)
```

**Comment by GeekDuanLian** [comment]
@willmcgugan 
Fair enough. I'll take your suggestion under advisement.
