### ISSUE TITLE
Long term project maintenance plans

### ISSUE THREAD

**Issue by ssbarnea** [willmcgugan/rich#237]
I liked rich as soon I found it and I would like to start using it on several CLI tools I am maintaining, like [ansible-lint](https://github.com/ansible/ansible-lint/pull/971) or [molecule](https://molecule.readthedocs.io/en/latest/). 

Still, I do have some concerns regarding long term future of the library as I see is hosted under a personal account. 

If you do not mind could you mention:
* are several cores available in case main contributor becomes unavailable?
* how willing to accept new cores?

Please note that this question is about risk mitigation. We all know how costly it can prove to fork or replace an unmaintained library. As I got my share of unlucky bets, now I am bit more cautious about adding new dependencies.

**Comment by willmcgugan** [comment]
Hi @ssbarnea 

Glad you like rich.

I'm the only core dev at the moment, while it's in active development. I am planning to solidify the core features so that there won't be need need for much ongoing work. At that point I'd seek a new maintainer. Possible one of the current set of contributors if they still have an interest.

I understand your concern, I've had similar experiences. In my experience projects become unmaintained because the code has collapsed under its own weight. This project is my chance to be more of a perfectionist that the day job, with high 90%s tests, documentation, and typing it should be easy to maintain well in to the future.
