### ISSUE TITLE
[BUG] emoji spacing issue

### ISSUE THREAD

**Issue by FedeClaudi** [willmcgugan/rich#408]
**Describe the bug**
It seems that the width of emojis is underestimated. When printing something like `:tada: message` the space between the emoji and the rest of the text is missing, similarly putting an emoji in a panel breaks things.
<img width="105" alt="image" src="https://user-images.githubusercontent.com/17436313/97105176-efe8d200-16b0-11eb-8a3b-4b67992c328e.png">

**To Reproduce**
```python
from rich.panel import Panel
from rich import print

print(Panel.fit(':tada:'))
print(':tada: message')
```

I've tried fixing this to send a PR but it turned out to be a bit too complicated.
The missing space in text issue can be fixed by adding a space in `_emoji_replace`:
```python
return get_emoji(emoji_name.lower(), emoji_code) + ' '
```

but it doesn't fix the panel and it feels a bit hacky..

**Platform**
Running on Mac

**Comment by willmcgugan** [comment]
Emoji are problematic. Some emoji take up 1 "cell" in the terminal, others take up 2. The only way to know which is which is to look it up in the unicode database. The problem is that different terminal apps use different versions of the unicode database, and there is no way to detect which is which.

The upshot is that emoji will be broken on some terminals with identical output.

<img width="987" alt="Screen Shot 2020-10-25 at 11 38 44" src="https://user-images.githubusercontent.com/554369/97106130-b49dd180-16b7-11eb-99d1-edc1257043fe.png">

Rich uses version 9 of the unicode database, which is not the newest or the oldest. At some point I'll ship Rich with several versions of the database which is a partial fix at best. I'm afraid there just isn't a good solution to this problem. 

BTW if you are using iTerm, open Preferences then go to Profile / Text tab and check "Use Unicode version 9+widths"

**Comment by FedeClaudi** [comment]
I see, it does sound fairly complicated indeed.

The iTerm thing fixes it though, thanks :)

**Comment by kpister** [comment]
@willmcgugan I am experiencing something similar with Hindi script (see screenshot). Is this caused by the same problem or should I create a separate issue?

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/4607361/97476591-9389ea80-191c-11eb-9643-fee425f88df3.png">

**Comment by willmcgugan** [comment]
@kpister I suspect that's the same problem. Do you have another terminal app you can try?

If you're using iTerm, try with the Unicode 9 widths.
