### ISSUE TITLE
[REQUEST] Multiline row support when text is too long to render in one line

### ISSUE THREAD

**Issue by fridex** [willmcgugan/rich#428]
**How would you improve Rich?**

We use rich to print reports in tables (see https://github.com/thoth-station/thamos/issues/541). However, some text printed in a 
 table row is too large to display in one line. It leads to truncating the text and adding three dots to it. Would it be possible to perform line wrap and print the content across multiple lines (but still have it in one row semantically)?

**What problem does it solved for you?**

Reports printed in tables would be human-readable.

**Comment by willmcgugan** [comment]
If you set the [overflow](https://rich.readthedocs.io/en/latest/console.html?highlight=overflow#overflow) for a column to "fold" it will insert breaks rather than truncating.

e.g.

```
table.add_column("Link", overflow="fold")
```

Another solution to this issue would be to make the column a link, with `table.add_row(f"[link {url}]{url}")`. This will make the link clickable even if it is truncated, and generally it will show the full link on hover. The downside is that it's not supported on all terminals.

**Comment by fridex** [comment]
Thanks! It works. I had to also remove `no_wrap=True`.

Thanks again for the suggestion and prompt response.
