### ISSUE TITLE
How to show progress bars for multi-processes using ProcessPoolExecutor?

### ISSUE THREAD

**Issue by Star9daisy** [willmcgugan/rich#436]
After I read the download.py that shows multi progress bars, I'm still confused that I cannot simply use ProcessPoolExecutor instead of ThreadPoolExecutor used by the example to show a valid progress bar. They just stucked there and I don't know why...

Is rich helpful for multiprocessing bars?

**Comment by willmcgugan** [comment]
Processes are different from threads in that they don't share memory, your worker processes will modify a copy of the Progress object rather than the original.

If you want finely grained progress from processes, you will have to send back progress information from the workers to the parent process. I don't think concurrent.futures has any way to do that. The `multiprocessing` modules does, although it is a little more work to set up.

Here are some related issues which might help.

https://github.com/willmcgugan/rich/issues/146
https://github.com/willmcgugan/rich/issues/121

**Comment by Star9daisy** [comment]
@willmcgugan Thanks a lot! I check #121 and that's what exactly what I need: a simple example to show how rich works in multiprocessing. One progress bar to show the total process also works for me :) 

Thank you again for this beautiful and powerful tool!
