### ISSUE TITLE
[BUG] Progress Bar looks worse in newer versions (on windows)

### ISSUE THREAD

**Issue by lagmoellertim** [willmcgugan/rich#467]
**Describe the bug**
The progressbar looks worse in newer versions (I tested v9.3.0 and v4.2.2) since it consists out of multiple seperate lines instead of a single, continuos line (worked fine in earlier versions).
Also, you can see in the pictures that in version 4.2.2, a question was printed as "[?]", while in 9.3.0, it became "[[?]]".

**To Reproduce**
I use rich in my project unsilence (https://github.com/lagmoellertim/unsilence), that's where the images come from, rich is used in this file (https://github.com/lagmoellertim/unsilence/blob/master/unsilence/command_line/EntryPoint.py). I ran it on Windows 10 version 20H2. 

**Platform**
Here are some examples (all run on Windows 10).
The upper row is an overview of multiple rich components (with finished progressbar), the lower row is always a picture of an unfinished progress bar.

New Version (v9.3.0)
| PyCharm Integrated Terminal | CMD | Windows Terminal |
| - | - | - |
| ![](https://i.imgur.com/bbaad0t.png) | ![](https://i.imgur.com/6gA0COk.png) | ![](https://i.imgur.com/CZ0Hw6A.png) |
| ![](https://i.imgur.com/DTQckhI.png) | ![](https://i.imgur.com/lPf6myz.png) | ![](https://i.imgur.com/BMV1lhQ.png) |

Old Version (v4.2.2)
| PyCharm Integrated Terminal | CMD | Windows Terminal |
| - | - | - |
| ![](https://i.imgur.com/2W1kJON.png) | ![](https://i.imgur.com/4oXnDdV.png) | ![](https://i.imgur.com/kwW7kYB.png) |
| ![](https://i.imgur.com/ubbGuVE.png)| ![](https://i.imgur.com/Fl2BoAu.png) | ![](https://i.imgur.com/iqXYY0A.png) |

**Comment by willmcgugan** [comment]
Thanks for the detailed bug report.

The progress bars default to the less pretty ascii-only version on Windows. This is because if you have bitmap fonts selected in command prompt properties then the bars characters don't display properly. Rich has no way to know which fonts are in use, so it picks the safe default. Given how ancient cmd.exe is, I'd suggest switching to Windows Terminal and recommend the same to your users if they care about how the progress bars look.

The issue with `[[?]]` is likely because of the change to escaping in version 5. See the [docs](https://rich.readthedocs.io/en/latest/markup.html#escaping) for the new method.

**Comment by lagmoellertim** [comment]
Thank you, can I somehow force the use of the prettier implementation?

**Comment by willmcgugan** [comment]
There's nothing exposed to modify that I'm afraid. I'm sure you could modify the BarColumn class, but bear in mind that would break it for a significant portion of your users.

**Comment by lagmoellertim** [comment]
That's right, I'm going to leave it as is then. I really appreciate your help!
