### ISSUE TITLE
[BUG] print sometimes ignores \r escape sequence

### ISSUE THREAD

**Issue by codemicro** [willmcgugan/rich#845]
**Describe the bug**
Rich doesn't appear to take notice of the `\r` escape sequence when it's included with a string as an argument to `rich.print`. If it's used in the `end` argument, it works as expected.

**To Reproduce**
```py
from rich import print as rprint

# behaviour with rich
rprint("Hello world!", end="\r")
rprint("Hi there, world!")

rprint("Hello world!\r", end="")
rprint("Hi there, world!")

print()

# standard behaviour
print("Hello world!", end="\r")
print("Hi there, world!")

print("Hello world!\r", end="")
print("Hi there, world!")
```

Outputs:

```cmd
❯ python .\test.py
Hi there, world!
Hello world!Hi there, world!

Hi there, world!
Hi there, world!
```

**Platform**
Running Windows 10, Powershell inside the new Windows Terminal and Rich 9.5.1

**Comment by willmcgugan** [comment]
Carriage returns break a number of features of rich, such as word wrap and alignment. Which is why they are stripped out. Not stripping it out of `end` was an oversight, but I'm inclined to leave it as it is for users who are certain they know what they are doing.

Most of what you might user `\r` for can be done with the new Live class, so it's not a great loss.

**Comment by codemicro** [comment]
Ah, that makes sense. In the situation I'm using it in, neither word wrap or alighnment are much of a concern, I'm just using Rich for the colours. The only plus I can see for `\r` compared to the `Live` class is that it's super simple for this use case.

Thanks for the prompt reply!
