### ISSUE TITLE
Alignment bug when using unicode symbol and color markup.

### ISSUE THREAD

**Issue by aroberge** [willmcgugan/rich#88]
An alignment bug can occur when creating tables using some unicode symbols together with added color markup.  Here is an example to demonstrate this:
```python
from rich.console import Console
from rich.table import Table

console = Console()

def print_table(char, color=False):
    table = Table(show_header=False)
    table.add_column()
    if color:
        table.add_row("[yellow]%s[/yellow]" % char)
    else:
        table.add_row(char)
    console.print(table)

print_table(">", color=False)
print_table("🡢", color=False)
print_table(">", color=True)
print_table("🡢", color=True)
```
Below is the result, using Python 3.8 and a Windows Terminal.
![image](https://user-images.githubusercontent.com/629698/82728787-fec5f580-9cc8-11ea-9900-03adf4a38857.png)

**Comment by willmcgugan** [comment]
This one had me scratching my head. It looks just like their is an extra space in there, but bizarrely there is no space in the text generated by Rich. I boiled the output down to the following:

```
>>> print("│\x1b[33m\U0001F862\x1b[0m│")
```

There is no space in there after the unicode arrow, but there is clearly a space when printed in the Windows terminal. The arrow doesn't render in OSX or Ubuntu terminal as the glyph isn't in the default font, but there is no extra space.

It has to be a bug in Windows terminal, quite an odd one at that. I'll report the issue on their repos. This is actually the second unicode issue I've found. I'll forgive Microsoft, since Windows Terminal is very new.

In the meantime, you might want to another [unicode arrow](http://xahlee.info/comp/unicode_arrows.html), some of which look similar.

**Comment by willmcgugan** [comment]
Not sure how long it will be before I get a response. There's a lot of issues for them to get through! https://github.com/microsoft/terminal/issues/6162

**Comment by aroberge** [comment]
Thanks. As far as I am concerned, you can close this issue.  

After experimenting with the look of a few unicode arrows, I decided to stick with the ascii combination `-->` to represent arrows as I thought it would be easier to see when projected on a screen.  However, when I noticed the alignment bug when I used that particular arrow, I thought I should create a minimal example to illustrate the bug in case it was something you could fix before others stumbled upon it.  It took me a while to figure out that it was the combination of color code and this unicode arrow. To be honest, I did not realize that other arrows were fine.

**Comment by willmcgugan** [comment]
Your example was very helpful in narrowing it down. It's a super weird bug.

I'll keep this issue open for now, just to keep track of that WT bug.

**Comment by DHowett** [comment]
(What was the other Unicode bug you found in WT? I’ve been working on our Unicode standards compliance w.r.t. character widths for the past couple weeks 😄)

**Comment by willmcgugan** [comment]
@DHowett https://github.com/microsoft/terminal/issues/6136

Great work on the windows terminal btw. Never seen Windows developers more excited!

**Comment by ankitbhatia** [comment]
I found another version of this bug when working with neovim in the windows terminal. Here's the link to the issue on the neovim github project. 
https://github.com/neovim/neovim/issues/12358#issue-622854022

**Comment by willmcgugan** [comment]
Closing this issue now. Looks like Microsoft are working on it.
