### ISSUE TITLE
[BUG] Can't print MagicMock.mock_calls

### ISSUE THREAD

**Issue by henryiii** [willmcgugan/rich#903]
**Describe the bug**
`rich.print` does not print something that print does, breaking with:

```
NotRenderableError: Unable to render (<console width=93 ColorSystem.TRUECOLOR>, ConsoleOptions(legacy_windows=False, min_width=1, max_width=93, is_terminal=False, encoding='utf-8', justify=None, overflow=None, no_wrap=False, highlight=None)); A str, Segment or object with __rich_console__ method is required
```

**To Reproduce**

```python
from unittest.mock import MagicMock

ListProxy = MagicMock("ListProxy")
y = ListProxy()
y[0] += 1
rich.print(*y.mock_calls)
```

If you remove the `rich.` _or_ the `*`, it works. I'm assuming it is suppose to fall back to repr/str, or is it supposed to break? The list containing it works just fine, just not singled out. This is a fairly unusual thing to print, I know, was working on a tutorial.

**Platform**

macOS 11 Intel, normally iTerm2 though I was in JupyterLab 3 for this, 9.7.0 from conda-forge.

**Comment by willmcgugan** [comment]
Mocks pretty much break introspection. The `unittest.mock._Call` objects which you are printing claims to have a `__rich__` method, so Rich treats it has supporting the Console protocol.

```python
>>> hasattr(y.mock_calls[0], "__rich__")
True
```

It doesn't support the Rich protocol of course, `hassattr` will return True for any attribute.

Printing the list works because the contents of the list are `repr`ed.

The solution may be to try and detect those mock call objects and special case them.

**Comment by willmcgugan** [comment]
Try v9.8.0 Should be fixed.

**Comment by henryiii** [comment]
I'll try it as soon as https://github.com/conda-forge/rich-feedstock/pull/47 goes in, thanks! (PS you can follow the instructions in the bot's PR description to setup auto merge on PRs; if things are not expected to break it makes conda-forge easier to maintain.

**Comment by henryiii** [comment]
It works now, thanks!
